#!/bin/bash
set -e  # exit immediately if a critical command fails

echo "🔄 Checking working directory status..."

# Automatically stash any uncommitted changes so checkout never blocks
if [[ -n $(git status -s) ]]; then
    echo "⚠️ Local changes detected. Auto-stashing changes..."
    git stash -u -m "Auto-stash generated by script at $(date)"
    STASHED=true
else
    STASHED=false
fi

# Step 1: Ensure you're on the main branch (forces creation/switch safely)
echo "🌿 Switching to 'main' branch..."
git checkout -B main || git switch -C main

# Bring your stashed changes back onto the main branch
if [ "$STASHED" = true ]; then
    echo "📥 Bringing your local changes back..."
    git stash pop --quiet || echo "⚠️ Stash pop had conflicts, please resolve them."
fi

# Step 2: Stage all changes
echo "📦 Staging changes..."
git add .

# Step 3: Commit changes (forces a commit even if no files changed to guarantee pipeline trigger)
echo "💾 Committing changes..."
if git diff-index --quiet HEAD --; then
    echo "ℹ️ No code changes detected. Forcing empty commit to trigger pipeline..."
    git commit --allow-empty -m "Force pipeline trigger at $(date)"
else
    git commit -m "DevSecOps GithubActions Docker Build"
fi

# Step 4: Push to remote
echo "🚀 Pushing to remote..."
git push -u origin main

echo "✅ All steps completed successfully and pipeline triggered!"