#!/bin/bash
set -e  # exit immediately if a critical command fails

echo "🔄 Checking working directory status..."

# 1. Automatically stash any uncommitted changes so checkout never blocks
if [[ -n $(git status -s) ]]; then
    echo "⚠️ Local changes detected. Auto-stashing changes..."
    git stash -u -m "Auto-stash generated by script at $(date)"
    STASHED=true
else
    STASHED=false
fi

# 2. Ensure you're on the main branch (forces creation/switch safely)
echo "🌿 Switching to 'main' branch..."
git checkout -B main || git switch -C main

# 3. Bring your stashed changes back onto the main branch
if [[ "$STASHED" = true ]]; then
    echo "📥 Bringing your local changes back..."
    git stash pop --quiet || echo "⚠️ Stash pop had conflicts, please resolve them."
fi

# 4. Stage all changes
echo "📦 Staging changes..."
git add .

# 5. Commit changes (forces an empty commit if no files changed to guarantee pipeline trigger)
echo "💾 Committing changes..."
if git diff-index --quiet HEAD --; then
    echo "ℹ️ No code changes detected. Forcing empty commit to trigger pipeline..."
    git commit --allow-empty -m "GithubActions Docker Build"
else
    git commit -m "DevSecOps GithubActions Docker Build"
fi

# 6. Sync with remote first (pull rebase) and push safely using force-with-lease
echo "🚀 Syncing and pushing to remote..."
git pull --rebase origin main || true
git push -u origin main --force-with-lease

echo "✅ All steps completed successfully and pipeline triggered!"