#!/bin/bash
set -e  # exit immediately if a critical command fails

echo "🔄 Checking working directory status..."

# 1. Automatically stash any local changes so they don't block anything
if [[ -n $(git status -s) ]]; then
    echo "⚠️ Local changes detected. Auto-stashing changes..."
    git stash -u -m "Auto-stash generated by script at $(date)"
    STASHED=true
else
    STASHED=false
fi

# 2. Switch to or create the 'pre-main' branch safely
echo "🔄 Switching to 'pre-main' branch..."
git checkout -B pre-main || git switch -C pre-main

# 3. Bring your stashed changes back onto the branch
if [ "$STASHED" = true ]; then
    echo "📥 Applying your local changes back..."
    git stash pop --quiet || echo "⚠️ Stash pop had conflicts, please resolve them."
fi

# 4. Stage any current file changes
git add .

# 5. Force a commit (even if no files changed) so Git always registers a new commit
echo "💾 Creating forced commit..."
git commit --allow-empty -m "DevSecOps CI at $(date)"

# 6. Sync with remote first (pull rebase) and push safely using force-with-lease
echo "🚀 Syncing and pushing to remote..."
git pull --rebase origin pre-main || true
git push -u origin pre-main --force-with-lease

echo "✅ Done! Pipeline should now trigger."