#!/bin/bash
set -e

# 1. Automatically stash any local changes so they don't block anything
if [[ -n $(git status -s) ]]; then
    echo "⚠️ Local changes detected. Auto-stashing changes..."
    git stash -u -m "Auto-stash generated by script at $(date)"
    STASHED=true
else
    STASHED=false
fi

# 2. Switch to or create the target branch safely (e.g., 'main' or 'pre-main')
echo "🔄 Switching branch..."
git checkout -B pre-main || git switch -C pre-main

# 3. Bring your stashed changes back onto the branch
if [ "$STASHED" = true ]; then
    echo "📥 Applying your local changes back..."
    git stash pop --quiet || echo "⚠️ Stash pop had conflicts, please resolve them."
fi

# 4. Stage any current file changes
git add .

# 5. Force a commit (even if no files changed) so Git always registers a new commit
echo "💾 Creating forced commit..."
git commit --allow-empty -m "Force pipeline trigger at $(date)"

# 6. Push to remote to guarantee GitHub Actions triggers
echo "🚀 Pushing to remote..."
git push -u origin pre-main

echo "✅ Done! Pipeline should now trigger."