sonar.projectKey=kaifmohammedkhan_resume-matcher-devops
sonar.organization=kaifmohammedkhan
sonar.host.url=https://sonarcloud.io

# Sources
sonar.sources=.

# Tests
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.test.jsx,**/*.spec.jsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions (no test files here)
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.git/**,**/.github/**,**/public/**,**/kubernetes/**,**/scripts/**,**/cypress/**,**/tests/**,**/*.config.js,**/*.json,**/jest.polyfills.js,**/jest.setup.js

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true
