apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: db
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret   # native Secret created via kubectl
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres   # ✅ avoids lost+found issue
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: resume-config
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None   # headless service for StatefulSet
  selector:
    app: db
