apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-matcher-sa
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-matcher-ghcr
  labels:
    app: resume-matcher-ghcr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-matcher-ghcr
  template:
    metadata:
      labels:
        app: resume-matcher-ghcr
    spec:
      serviceAccountName: resume-matcher-sa
      automountServiceAccountToken: false

      imagePullSecrets:
        - name: ghcr-secret

      initContainers:
        - name: wait-for-db
          image: postgres:15
          command:
            - sh
            - -c
            - until pg_isready -h postgres -p 5432; do echo waiting for db; sleep 2; done;

      containers:
        - name: resume-matcher-ghcr
          image: ghcr.io/kaifmohammedkhan/resume-matcher-devops:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-key
                  key: API_KEY
            - name: GOOGLE_CX_ID
              valueFrom:
                secretKeyRef:
                  name: google-cx-id
                  key: CX_ID
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: logs
              mountPath: /app/logs
            - name: config-volume
              mountPath: /app/config
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

      volumes:
        - name: uploads
          emptyDir: {}

        - name: logs
          emptyDir: {}

        - name: config-volume
          configMap:
            name: resume-config