apiVersion: v1
kind: Secret
metadata:
  name: google-api-key
type: Opaque
stringData:
  API_KEY: "AIzaSyBExXAVBbzwhpWmjguzfAp3OxlQPy5ibjk,AIzaSyBcrj0PwngPmTUx29fxA1xvORajqEwSvE4,AIzaSyDnPolnpZT-G9t_qkLgAr922bhgDksv75s,AIzaSyD9G6sFNeqfRFh3GCyoweCjY1Fh2wY5M8Q,AIzaSyDJIxuc0Xbag1Z60smHXDg8-NPL6lfA1Qk,AIzaSyDmysgRzo-7hVK-xniYwgjtYe4WdnS8MSw,AIzaSyDXN_iEk7UuJrdtQMoEzPazkbJUuj1bI38,AIzaSyAtYdX_t6IVSBtKa2Uw7H8Aw6w0QnlpjRc,AIzaSyC6ncIjuNgEo7MPK7gH3723X8Pvs5Oxjqk,AIzaSyCSFMzrE0Bjc3fMpJMFqTxSRdP314Rlv0I,AIzaSyByET-77gw-NmNx_cmoekJYn5_t6CaLsZk"
