apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecretName }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_NAME: {{ .Values.secrets.dbName }}
