apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.ports.http }}
            - containerPort: {{ .Values.app.ports.metrics }}
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.googleApiSecretName }}
                  key: API_KEY
            - name: GOOGLE_CX_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.googleCxSecretName }}
                  key: CX_ID
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: DB_NAME
            - name: DB_HOST
              value: {{ .Release.Name }}-db
            - name: DB_PORT
              value: "{{ .Values.db.servicePort }}"
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: uploads
          emptyDir: {}
        - name: logs
          emptyDir: {}
