name: CI & Security Pipeline

on:
  push:
    branches: [ "pre-main" ]
  pull_request:
    branches: [ "pre-main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  owasp:
    uses: ./.github/workflows/ci-owasp.yaml
    secrets: inherit

  test:
    uses: ./.github/workflows/ci-test.yaml
    secrets: inherit

  sonarcloud:
    needs: test
    uses: ./.github/workflows/ci-sonarcloud.yaml
    secrets: inherit

  trivy:
    needs: sonarcloud
    uses: ./.github/workflows/ci-trivy.yaml
    secrets: inherit

  gitleaks:
    needs: trivy
    uses: ./.github/workflows/ci-gitleaks.yaml
    secrets: inherit

  commit-signing:
    needs: gitleaks
    uses: ./.github/workflows/ci-commit-signing.yaml
    secrets: inherit

  email:
    needs: [test, sonarcloud, trivy, gitleaks, commit-signing]
    uses: ./.github/workflows/ci-email.yaml
    secrets: inherit
