name: CI & Security Pipeline

on:
  push:
    branches: [ "pre-main" ]
  pull_request:
    branches: [ "pre-main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  owasp:
    uses: ./.github/workflows/ci-owasp.yaml
    secrets: inherit

  test:
    uses: ./.github/workflows/ci-test.yaml
    secrets: inherit

  sonarcloud:
    needs: test
    uses: ./.github/workflows/ci-sonarcloud.yaml
    secrets: inherit

  trivy:
    needs: sonarcloud
    uses: ./.github/workflows/ci-trivy.yaml
    secrets: inherit

  security-checks:
    needs: trivy
    uses: ./.github/workflows/ci-security-checks.yaml
    secrets: inherit

  email:
    needs: [test, sonarcloud, trivy, security-checks]
    uses: ./.github/workflows/ci-email.yaml
    secrets: inherit
