name: Jenkins Agent Runner

on:
  workflow_dispatch:
    inputs:
      jenkins_url:
        description: 'Jenkins Controller URL'
        required: true
      agent_name:
        description: 'Jenkins Agent Name'
        required: true
      agent_secret:
        description: 'Jenkins Agent Secret'
        required: true

jobs:
  run-jenkins-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java Runtime
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare Agent Working Directory
        run: |
          mkdir -p /home/runner/agent/workspace

      - name: Download Jenkins Agent JAR
        run: |
          CLEAN_URL=$(echo "${{ inputs.jenkins_url }}" | sed 's/\/*$//')
          curl -H "ngrok-skip-browser-warning: true" -L -sO "${CLEAN_URL}/jnlpJars/agent.jar"

      - name: Run Jenkins Agent
        run: |
          CLEAN_URL=$(echo "${{ inputs.jenkins_url }}" | sed 's/\/*$//')
          java -Dfile.encoding=UTF-8 \
            -jar agent.jar \
            -url "${CLEAN_URL}" \
            -secret "${{ inputs.agent_secret }}" \
            -name "${{ inputs.agent_name }}" \
            -webSocket \
            -webSocketHeader "ngrok-skip-browser-warning=true" \
            -workDir "/home/runner/agent"