name: QA Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  cypress-e2e:
    uses: ./.github/workflows/qa-cypress.yaml
    secrets: inherit

  k6-smoke-test:
    needs:
      - cypress-e2e
    if: needs.cypress-e2e.result == 'success'
    uses: ./.github/workflows/qa-k6-smoke.yaml
    secrets: inherit

  k6-load-test:
    needs:
      - k6-smoke-test
    if: needs.k6-smoke-test.result == 'success'
    uses: ./.github/workflows/qa-k6-load.yaml
    secrets: inherit

  qa-pass:
    needs:
      - cypress-e2e
      - k6-smoke-test
      - k6-load-test
    if: always()
    uses: ./.github/workflows/qa-report.yaml
    with:
      cypress_result: ${{ needs.cypress-e2e.result }}
      k6_smoke_result: ${{ needs.k6-smoke-test.result }}
      k6_load_result: ${{ needs.k6-load-test.result }}
    secrets: inherit